from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from .extensions import db


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(120), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)

    # Mark whether the account has admin privileges.
    is_admin = db.Column(db.Boolean, default=False, nullable=False)

    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    files = db.relationship('SharedFile', backref='uploader', lazy=True)
    reports = db.relationship('FileReport', backref='reporter', lazy=True)

    def set_password(self, raw_password: str) -> None:
        # Store a secure hash instead of saving the plain password.
        self.password_hash = generate_password_hash(raw_password)

    def check_password(self, raw_password: str) -> bool:
        # Compare the provided password against the stored hash.
        return check_password_hash(self.password_hash, raw_password)


class Major(db.Model):
    __tablename__ = 'majors'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False, unique=True)
    courses = db.relationship('Course', backref='major', lazy=True, cascade='all, delete-orphan')


class Course(db.Model):
    __tablename__ = 'courses'

    id = db.Column(db.Integer, primary_key=True)
    major_id = db.Column(db.Integer, db.ForeignKey('majors.id'), nullable=False)
    name = db.Column(db.String(120), nullable=False)
    files = db.relationship('SharedFile', backref='course', lazy=True, cascade='all, delete-orphan')


class SharedFile(db.Model):
    __tablename__ = 'shared_files'

    id = db.Column(db.Integer, primary_key=True)
    course_id = db.Column(db.Integer, db.ForeignKey('courses.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    filename = db.Column(db.String(255), nullable=False)
    storage_name = db.Column(db.String(255), nullable=False, unique=True)

    # File visibility status: approved, rejected, or pending_review.
    status = db.Column(db.String(30), default='approved', nullable=False)

    # Reason generated by the automatic reviewer or admin action.
    review_reason = db.Column(db.String(255), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    reports = db.relationship('FileReport', backref='file', lazy=True, cascade='all, delete-orphan')


class FileReport(db.Model):
    __tablename__ = 'file_reports'

    id = db.Column(db.Integer, primary_key=True)
    file_id = db.Column(db.Integer, db.ForeignKey('shared_files.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    reason = db.Column(db.String(255), default='Reported by user', nullable=False)

    # Report status: open, accepted, or rejected.
    status = db.Column(db.String(30), default='open', nullable=False)
    admin_note = db.Column(db.String(255), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
